const Menu = [
  {
    id: 1,
    title: 'Stuffed Artichokes',
    category: 'Appetizers',
    price: 25.5,
    desc: 'Artichokes, Ricotta Cheese, Garlic, Breadcrumbs, Parmesan',
image: 'https://www.listsforall.com/wp-content/uploads/2017/10/Stuffed-Artichokes.jpg.webp',
  },
  {
    id: 2,
    title: 'Hot Ham and cheese party rolls',
    category: 'Appetizers',
    price: 40.0,
    desc: 'Pillsbury Pizza Crust Dough, Deli Ham, Swiss Cheese',
image: 'https://www.listsforall.com/wp-content/uploads/2017/10/Hot-Ham-and-Cheese-Party-Rolls.jpg.webp',
  },
  {
    id: 3,
    title: 'Neiman marcus dip',
    category: 'Appetizers',
    price: 10.0,
    desc: 'Shredded Mixed or Cheddar Cheese, Green Onions, Slivered Almonds, Bacon, Mayonaise',
    image: 'https://www.listsforall.com/wp-content/uploads/2017/10/Neiman-Marcus-Dip.jpg.webp',
  },
  {
    id: 4,
    title: 'Meatball stuffed Buns',
    category: 'Appetizers',
    price: 39.0,
    desc: ' Fully Cooked Italian Meatballs, Pillsbury Biscuits, String Cheese, Parmesan Cheese, Marinara Sauce',
image: 'https://www.listsforall.com/wp-content/uploads/2017/10/Meatball-Stuffed-Buns.jpg.webp',
  },
  {
    id: 5,
    title: 'Greek Salad',
    category: 'MainDishes',
    price: 25.5,
    desc: 'Tomatoes, green bell pepper, sliced cucumber onion, olives, and feta cheese.',
image: 'https://mediacity.co.in/delici/static/media/menu-image-15.e232ca83e1772b223de8.jpg',
  },
  {
    id: 6,
    title: 'Opu fish',
    category: 'MainDishes',
    price: 40.0,
    desc: 'Vegetables, cheeses, ground meats, tomato sauce, seasonings and spices.',
    image: 'https://mediacity.co.in/delici/static/media/menu-image-14.cc993aeb8cae1e7c3ae7.jpg',
  },
  {
    id: 7,
    title: 'Butternut Pumpkin',
    category: 'MainDishes',
    price: 10.0,
    desc: 'Typesetting industry lorem Lorem Ipsum is simply dummy text of the priand.',
image: 'https://mediacity.co.in/delici/static/media/menu-image-13.def913c8d8e23413a075.jpg',
  },
  {
    id: 8,
    title: 'Tokusen Wagyu NEW',
    category: 'MainDishes',
    price: 39.0,
    desc: 'Vegetables, cheeses, ground meats, tomato sauce, seasonings and spices.',
image: 'https://mediacity.co.in/delici/static/media/menu-image-16.7c1fc9761621b4d06bbf.jpg',
  },
  {
    id: 9,
    title: 'Easy cornflake tart',
    category: 'Desserts',
    price: 25.5,
    desc: 'With a pastry case and jam base, it is delicious served with custard',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/cornflake-cake-f773778.jpg?quality=90&webp=true&resize=300,272',
  },
  {
    id: 10,
    title: 'Damson crumble',
    category: 'Desserts',
    price: 40.0,
    desc: 'The damsons will contain stones, so remember to warn people to remove them as they eat',
image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/damson_crumble-d2ab73c.jpg?quality=90&webp=true&resize=300,272',
  },
  {
    id: 11,
    title: 'Cherry & almond frangipane galette',
    category: 'Desserts',
    price: 10.0,
    desc: 'Use spelt pastry for this free-form pie, as its nuttiness complements the frangipane.',
image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/cherry-almond-frangipane-galette-07807dc.jpg?quality=90&webp=true&resize=300,272',
  },
  {
    id: 12,
    title: 'Blackberry & lemon fool',
    category: 'Desserts',
    price: 39.0,
    desc: 'Create this delicious pudding in just 10 minutes, then pop it in the fridge. Serve in glasses and garnish with fresh blackberries for an elegant summer dessert',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/fools-a48cee6.jpg?quality=90&webp=true&resize=300,272',
  },
   {
    id: 13,
    title: 'Martini',
    category: 'Drinks',
    price: 5.0,
    desc: 'A classic cocktail made with gin or vodka and vermouth typically garnished with an olive or a twist of lemon.',
image: 'https://bing.com/th?id=OSK.1775c03beafde39a4f5114671161c863',
  },
  {
    id: 14,
    title: 'Mojito',
    category: 'Drinks',
    price: 4.5,
    desc: 'A refreshing Cuban cocktail made with white rum, sugar, lime juice, soda water, and mint.',
image: 'https://th.bing.com/th/id/OIP.36oPsnLYFNqn_5ARKMCC_gHaE6?pid=ImgDet&rs=1',
  },
   {
    id: 15,
    title: 'Espresso',
    category: 'Drinks',
    price: 6.0,
    desc: 'A concentrated coffee beverage brewed by forcing hot water through finely ground coffee beans.',
    image: 'https://live.staticflickr.com/8519/8508902022_cfa9e04699.jpg',
  },
  {
    id: 16,
    title: 'Margarita',
    category: 'Drinks',
    price: 7.5,
    desc: 'A popular Mexican cocktail made with tequila, triple sec, and lime juice, usually served with a salted rim.',
    image: 'https://bing.com/th?id=OSK.06bdb5fbf963c1591032bcb84598189b',
  },
];

export default Menu;